### PR TITLE
MIGR-198: Support updating in the scripts

### PR DESCRIPTION
**Pull request by mbriskar**

### CODE REVIEW

**Comment by mbriskar** [comment]
I tested it on the windows machine

**Comment by lincolnthree** [comment]
I think these scripts can also run windup again after performing the update, no?

**Comment by lincolnthree** [comment]
Just like the Forge scripts.

**Comment by lincolnthree** [comment]
Put on hold as this has been de-prioritized. Needs to be looked at and reopened once it is prioritized again.

**Pull request closed without merging**
