### PR TITLE
WINDUP-3602 Add config for jdk17

### PR DESCRIPTION
**Pull request by carlosthe19916**
https://issues.redhat.com/browse/WINDUP-3602

Changes required for making Windup CLI able to run with both JDK11 and JDK17

### CODE REVIEW

**Comment by PhilipCattanach** [comment]
@carlosthe19916 - I have done some testing of this PR and I was delighted to see entirely consistent results when running an eap:7 and cloud-readiness analysis of the sample ear file using 
Temurin 11.0.17,  17-open, Temurin 17.0.6  and Oracle 17.0.6
As a final test I tried running an analysis using 19.0.2-open.  I was expecting the validation to block it, but it worked. When I have had a look at the CLI script it looks like it should prevent the analysis from executing, but it doesn't. Can you investigate please?

**Comment by PhilipCattanach** [comment]
@carlosthe19916 
I repeated the test and now I'm having problems with running Java 17
Just to be clear I have built the cli with the master branch of windup and windup-rulesets and this PR

I am getting this error:
Using java version 17-open in this shell.
[pcattana@pcattana bin]$ ./windup-cli --input ../samples/jee-example-app-1.0.0.ear --target eap:7 cloud-readiness --output $HOME/MTA_Output/jee-example17-open
Increasing the maximum of open files to 10000.
Using the CLI at /home/pcattana/windup-cli-6.2.0-SNAPSHOT
 Error: a Java 11 or 17 JRE is required to run WINDUP; found [/home/pcattana/.sdkman/candidates/java/17-open/bin/java -version == openjdk version "17" 2021-09-14
OpenJDK Runtime Environment (build 17+35-2724)
OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)].

**Comment by PhilipCattanach** [comment]
@carlosthe19916 The CLI is still allowing me to run it using Java 19.
If I try to use java 8 it stops immediately with the expected error message.
Are you going to tighten up the validation to ensue only 11 and 17 are permitted?

**Comment by carlosthe19916** [comment]
@PhilipCattanach I have pushed a new commit that should make windup work only with jdk 11 or 17. May I ask you to give it a test again please?

**Comment by PhilipCattanach** [comment]
Tested successfully on RHEL CSB with Java 11 (Open and Temurin), Java 17 Open and Oracle.
Java 8 Open and 19 Open were flagged as invalid.

**Pull request merged**
